[package]
name = "elixlsx_native"
version = "0.1.0"
authors = []

[lib]
name = "elixlsx_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.18.0"
rustler_codegen = "0.18.0"
lazy_static = "1.0"
chrono = "0.4"
regex = "1"

[profile.release] 
lto  =  true
